## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("/Users/darrenlemyacrawford/Desktop/Class folder/World_Weather_Analysis/Weather_Database/Vacation_Itinerary/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Natchitoches,US,88.65,overcast clouds,31.7668,-93.1335,Super 8 by Wyndham Natchitoches
1,2,Komsomolskiy,UZ,77.72,few clouds,40.4272,71.7189,Ikathouse
2,3,Puerto Ayora,EC,76.96,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
3,9,Saint-Louis,SN,85.19,clear sky,16.3333,-15.0000,NaN
4,19,Atuona,PF,77.54,clear sky,-9.8000,-139.0333,Villa Enata

In [3]:
vacation_df.dropna()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Natchitoches,US,88.65,overcast clouds,31.7668,-93.1335,Super 8 by Wyndham Natchitoches
1,2,Komsomolskiy,UZ,77.72,few clouds,40.4272,71.7189,Ikathouse
2,3,Puerto Ayora,EC,76.96,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
4,19,Atuona,PF,77.54,clear sky,-9.8000,-139.0333,Villa Enata
5,24,Fortuna,US,76.93,overcast clouds,40.5982,-124.1573,Super 8 by Wyndham Fortuna
...,...,...,...,...,...,...,...,...
193,679,Curaca,BR,83.26,overcast clouds,-8.9903,-39.9094,Hotel Recanto Campestre
194,681,Umm Lajj,SA,88.16,clear sky,25.0213,37.2685,Moon light Furnished Units
195,683,Jamiltepec,MX,81.72,broken clouds,16.2833,-97.8167,Hotel Cádiz
196,684,Urucara,BR,75.97,overcast clouds,-2.5364,-57.7600,Pousada Maria Bonita
197,688,Makakilo City,US,82.56,clear sky,21.3469,-158.0858,Marriott's Ko Olina Beach Club

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Ewa Beach") & (vacation_df["Country"] == "US")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Ewa Beach") & (vacation_df["Country"] == "US")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Ahuimanu") & (vacation_df["Country"] == "US")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Nanakuli") & (vacation_df["Country"] == "US")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Makakilo City") & (vacation_df["Country"] == "US")]

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start["Lat"].to_numpy()[0], vacation_start ["Lng"].to_numpy()[0])
end = (vacation_end["Lat"].to_numpy()[0], vacation_end ["Lng"].to_numpy()[0])
stop1 = (vacation_stop1["Lat"].to_numpy()[0], vacation_stop1 ["Lng"].to_numpy()[0])
stop2 = (vacation_stop2["Lat"].to_numpy()[0], vacation_stop2 ["Lng"].to_numpy()[0])
stop3 = (vacation_stop3["Lat"].to_numpy()[0], vacation_stop3 ["Lng"].to_numpy()[0])

print(f"The starting point Latitude & Longitude: {start}")
print(f"The ending point (same as starting point) Latitude & Longitude: {end}")
print(f"The first stop's Latitude & Longitude (second of four locations): {stop1}")
print(f"The second stop's Latitude & Longitude (third city on the itinerary): {stop2}")
print(f"The third stop's Latitude & Longitude (fourth city...): {stop3}")

The starting point Latitude & Longitude: (21.3156, -158.0072)
The ending point (same as starting point) Latitude & Longitude: (21.3156, -158.0072)
The first stop's Latitude & Longitude (second of four locations): (21.4447, -157.8378)
The second stop's Latitude & Longitude (third city on the itinerary): (21.3906, -158.1547)
The third stop's Latitude & Longitude (fourth city...): (21.3469, -158.0858)

In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

# latitude-longitude pairs
start = (21.3156, -158.0072)
end = (21.3156, -158.0072)
stop1 = (21.4447, -157.8378)
stop2 = (21.3906, -158.1547)
stop3 = (21.3469, -158.0858)

fig = gmaps.figure()
start_stop3 = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], 
                                                travel_mode='DRIVING')
fig.add_layer(start_stop3)
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3,vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,401,Ewa Beach,US,85.95,scattered clouds,21.3156,-158.0072,Base Lodging
1,431,Ahuimanu,US,85.71,broken clouds,21.4447,-157.8378,Paradise Bay Resort
2,432,Nanakuli,US,85.95,scattered clouds,21.3906,-158.1547,Camp Pālehua
3,688,Makakilo City,US,82.56,clear sky,21.3469,-158.0858,Marriott's Ko Olina Beach Club
4,401,Ewa Beach,US,85.95,scattered clouds,21.3156,-158.0072,Base Lodging

In [10]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info2 = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations2 = itinerary_df[["Lat", "Lng"]]

In [11]:
# 11a. Add a marker layer for each city to the map.
locations2 = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations2, info_box_content=hotel_info2)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))